--------------------------------------------------------
--  File created - Çarþamba-Haziran-03-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "E1818939"."ADMIN" 
   (	"ADMINID" NUMBER, 
	"ADMINPASSWORD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "E1818939"."COURSE" 
   (	"COURSEID" NUMBER(*,0), 
	"DEPTID" NUMBER(*,0), 
	"COURSENAME" VARCHAR2(100 BYTE), 
	"CREDIT" NUMBER(*,0), 
	"SEMESTER" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "E1818939"."DEPARTMENT" 
   (	"DEPTID" NUMBER(*,0), 
	"FACID" NUMBER(*,0), 
	"DEPTNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENROLLGRADUATE
--------------------------------------------------------

  CREATE TABLE "E1818939"."ENROLLGRADUATE" 
   (	"STUDENTID" NUMBER(*,0), 
	"SECNO" NUMBER(*,0), 
	"COURSEID" NUMBER(*,0), 
	"YEAR" VARCHAR2(30 BYTE), 
	"GRADE" VARCHAR2(20 BYTE), 
	"PROGRAM" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENROLLSPECIAL
--------------------------------------------------------

  CREATE TABLE "E1818939"."ENROLLSPECIAL" 
   (	"STUDENTID" NUMBER(*,0), 
	"SECNO" NUMBER(*,0), 
	"COURSEID" NUMBER(*,0), 
	"YEAR" VARCHAR2(30 BYTE), 
	"GRADE" VARCHAR2(20 BYTE), 
	"PROGRAM" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENROLLUNDERGRADUATE
--------------------------------------------------------

  CREATE TABLE "E1818939"."ENROLLUNDERGRADUATE" 
   (	"STUDENTID" NUMBER(*,0), 
	"SECNO" NUMBER(*,0), 
	"COURSEID" NUMBER(*,0), 
	"YEAR" VARCHAR2(30 BYTE), 
	"GRADE" VARCHAR2(20 BYTE), 
	"PROGRAM" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACULTY
--------------------------------------------------------

  CREATE TABLE "E1818939"."FACULTY" 
   (	"FACID" NUMBER(*,0), 
	"FACNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRADUATE
--------------------------------------------------------

  CREATE TABLE "E1818939"."GRADUATE" 
   (	"STUDENTID" NUMBER(*,0), 
	"DEPTID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"NATID" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"CGPA" FLOAT(126), 
	"UNDERGRADSCHOOL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREREQUISITE
--------------------------------------------------------

  CREATE TABLE "E1818939"."PREREQUISITE" 
   (	"COURSEID" NUMBER(*,0), 
	"PREID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFADVISEDGRAD
--------------------------------------------------------

  CREATE TABLE "E1818939"."PROFADVISEDGRAD" 
   (	"EMPID" NUMBER(*,0), 
	"STUDENTID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFADVISEDSPEC
--------------------------------------------------------

  CREATE TABLE "E1818939"."PROFADVISEDSPEC" 
   (	"EMPID" NUMBER(*,0), 
	"STUDENTID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFADVISEDUNDERGRAD
--------------------------------------------------------

  CREATE TABLE "E1818939"."PROFADVISEDUNDERGRAD" 
   (	"EMPID" NUMBER(*,0), 
	"STUDENTID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFESSOR
--------------------------------------------------------

  CREATE TABLE "E1818939"."PROFESSOR" 
   (	"EMPID" NUMBER(*,0), 
	"DEPTID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"NATID" VARCHAR2(11 BYTE), 
	"SALARY" NUMBER(*,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PHONENO" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"ISCHAIR" VARCHAR2(1 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"OFFICE" VARCHAR2(30 BYTE), 
	"GRADSCHOOL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROGRAM
--------------------------------------------------------

  CREATE TABLE "E1818939"."PROGRAM" 
   (	"PROGID" NUMBER(*,0), 
	"DEPTID" NUMBER(*,0), 
	"LEVELPROG" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROGRAMRELCOURSE
--------------------------------------------------------

  CREATE TABLE "E1818939"."PROGRAMRELCOURSE" 
   (	"PROGID" NUMBER(*,0), 
	"COURSEID" NUMBER(*,0), 
	"DEPTID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTERGRAD
--------------------------------------------------------

  CREATE TABLE "E1818939"."REGISTERGRAD" 
   (	"PROGID" NUMBER(*,0), 
	"STUDENTID" NUMBER(*,0), 
	"DEPTID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTERSPEC
--------------------------------------------------------

  CREATE TABLE "E1818939"."REGISTERSPEC" 
   (	"PROGID" NUMBER(*,0), 
	"STUDENTID" NUMBER(*,0), 
	"DEPTID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTERUNDER
--------------------------------------------------------

  CREATE TABLE "E1818939"."REGISTERUNDER" 
   (	"PROGID" NUMBER(*,0), 
	"STUDENTID" NUMBER(*,0), 
	"DEPTID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SECTION
--------------------------------------------------------

  CREATE TABLE "E1818939"."SECTION" 
   (	"SECNO" NUMBER(*,0), 
	"COURSEID" NUMBER(*,0), 
	"CAPACITY" NUMBER(*,0), 
	"CAPACITYUSED" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SECTIONINFO
--------------------------------------------------------

  CREATE TABLE "E1818939"."SECTIONINFO" 
   (	"COURSEID" NUMBER(*,0), 
	"SECNO" NUMBER(*,0), 
	"DATESEC" VARCHAR2(30 BYTE), 
	"LOCATION" VARCHAR2(30 BYTE), 
	"STARTHOUR" VARCHAR2(30 BYTE), 
	"ENDHOUR" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SECTIONPROFESSOR
--------------------------------------------------------

  CREATE TABLE "E1818939"."SECTIONPROFESSOR" 
   (	"COURSEID" NUMBER(*,0), 
	"SECNO" NUMBER(*,0), 
	"EMPID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPECIALSTUDENT
--------------------------------------------------------

  CREATE TABLE "E1818939"."SPECIALSTUDENT" 
   (	"STUDENTID" NUMBER(*,0), 
	"DEPTID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"NATID" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"INSTITUTION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "E1818939"."STAFF" 
   (	"EMPID" NUMBER(*,0), 
	"DEPTID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"NATID" VARCHAR2(11 BYTE), 
	"SALARY" NUMBER(*,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PHONENO" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"RESPONSIBILITY" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UNDERGRADUATE
--------------------------------------------------------

  CREATE TABLE "E1818939"."UNDERGRADUATE" 
   (	"STUDENTID" NUMBER(*,0), 
	"DEPTID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"NATID" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"CGPA" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."ADMIN_PK" ON "E1818939"."ADMIN" ("ADMINID", "ADMINPASSWORD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021843
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021843" ON "E1818939"."COURSE" ("COURSEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021789
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021789" ON "E1818939"."DEPARTMENT" ("DEPTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021867
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021867" ON "E1818939"."ENROLLGRADUATE" ("STUDENTID", "SECNO", "COURSEID", "YEAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021870
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021870" ON "E1818939"."ENROLLSPECIAL" ("STUDENTID", "SECNO", "COURSEID", "YEAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021864
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021864" ON "E1818939"."ENROLLUNDERGRADUATE" ("STUDENTID", "SECNO", "COURSEID", "YEAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021788
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021788" ON "E1818939"."FACULTY" ("FACID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021829
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021829" ON "E1818939"."GRADUATE" ("STUDENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021884
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021884" ON "E1818939"."PREREQUISITE" ("COURSEID", "PREID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021858
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021858" ON "E1818939"."PROFADVISEDGRAD" ("STUDENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021861
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021861" ON "E1818939"."PROFADVISEDSPEC" ("STUDENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021855
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021855" ON "E1818939"."PROFADVISEDUNDERGRAD" ("STUDENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021799
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021799" ON "E1818939"."PROFESSOR" ("EMPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021873
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021873" ON "E1818939"."PROGRAM" ("PROGID", "DEPTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021845
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021845" ON "E1818939"."SECTION" ("SECNO", "COURSEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021852
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021852" ON "E1818939"."SECTIONPROFESSOR" ("COURSEID", "SECNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021819
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021819" ON "E1818939"."SPECIALSTUDENT" ("STUDENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021810
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021810" ON "E1818939"."STAFF" ("EMPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021838
--------------------------------------------------------

  CREATE UNIQUE INDEX "E1818939"."SYS_C0021838" ON "E1818939"."UNDERGRADUATE" ("STUDENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "E1818939"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ADMINID", "ADMINPASSWORD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "E1818939"."ADMIN" MODIFY ("ADMINPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."ADMIN" MODIFY ("ADMINID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "E1818939"."COURSE" ADD PRIMARY KEY ("COURSEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "E1818939"."COURSE" MODIFY ("SEMESTER" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."COURSE" MODIFY ("CREDIT" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."COURSE" MODIFY ("COURSENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "E1818939"."DEPARTMENT" ADD PRIMARY KEY ("DEPTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENROLLGRADUATE
--------------------------------------------------------

  ALTER TABLE "E1818939"."ENROLLGRADUATE" ADD PRIMARY KEY ("STUDENTID", "SECNO", "COURSEID", "YEAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENROLLSPECIAL
--------------------------------------------------------

  ALTER TABLE "E1818939"."ENROLLSPECIAL" ADD PRIMARY KEY ("STUDENTID", "SECNO", "COURSEID", "YEAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENROLLUNDERGRADUATE
--------------------------------------------------------

  ALTER TABLE "E1818939"."ENROLLUNDERGRADUATE" ADD PRIMARY KEY ("STUDENTID", "SECNO", "COURSEID", "YEAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACULTY
--------------------------------------------------------

  ALTER TABLE "E1818939"."FACULTY" ADD PRIMARY KEY ("FACID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRADUATE
--------------------------------------------------------

  ALTER TABLE "E1818939"."GRADUATE" ADD CONSTRAINT "CHECK_LENGRAD" CHECK (studentID <= 999999 and studentID >=100000) ENABLE;
  ALTER TABLE "E1818939"."GRADUATE" ADD CONSTRAINT "EMAIL_CHACKGRAD" CHECK (email like '%@%') ENABLE;
  ALTER TABLE "E1818939"."GRADUATE" ADD PRIMARY KEY ("STUDENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "E1818939"."GRADUATE" MODIFY ("UNDERGRADSCHOOL" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."GRADUATE" MODIFY ("CGPA" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."GRADUATE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."GRADUATE" MODIFY ("NATID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."GRADUATE" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."GRADUATE" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREREQUISITE
--------------------------------------------------------

  ALTER TABLE "E1818939"."PREREQUISITE" ADD PRIMARY KEY ("COURSEID", "PREID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFADVISEDGRAD
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROFADVISEDGRAD" MODIFY ("EMPID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."PROFADVISEDGRAD" ADD PRIMARY KEY ("STUDENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFADVISEDSPEC
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROFADVISEDSPEC" ADD PRIMARY KEY ("STUDENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFADVISEDUNDERGRAD
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROFADVISEDUNDERGRAD" ADD PRIMARY KEY ("STUDENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFESSOR
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROFESSOR" ADD PRIMARY KEY ("EMPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "E1818939"."PROFESSOR" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."PROFESSOR" ADD CONSTRAINT "CHECK_LENPROF" CHECK (empId <= 9999 and empID >=1000) ENABLE;
  ALTER TABLE "E1818939"."PROFESSOR" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."PROFESSOR" MODIFY ("NATID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."PROFESSOR" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."PROFESSOR" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."PROFESSOR" ADD CONSTRAINT "EMAIL_CHECKPROF" CHECK (email like '%@%') ENABLE;
--------------------------------------------------------
--  Constraints for Table PROGRAM
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROGRAM" ADD CONSTRAINT "SYS_C0021873" PRIMARY KEY ("PROGID", "DEPTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "E1818939"."PROGRAM" MODIFY ("DEPTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROGRAMRELCOURSE
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROGRAMRELCOURSE" MODIFY ("COURSEID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."PROGRAMRELCOURSE" MODIFY ("PROGID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."PROGRAMRELCOURSE" MODIFY ("DEPTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGISTERGRAD
--------------------------------------------------------

  ALTER TABLE "E1818939"."REGISTERGRAD" MODIFY ("STUDENTID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."REGISTERGRAD" MODIFY ("PROGID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."REGISTERGRAD" MODIFY ("DEPTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGISTERSPEC
--------------------------------------------------------

  ALTER TABLE "E1818939"."REGISTERSPEC" MODIFY ("STUDENTID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."REGISTERSPEC" MODIFY ("PROGID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."REGISTERSPEC" MODIFY ("DEPTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGISTERUNDER
--------------------------------------------------------

  ALTER TABLE "E1818939"."REGISTERUNDER" MODIFY ("STUDENTID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."REGISTERUNDER" MODIFY ("PROGID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."REGISTERUNDER" MODIFY ("DEPTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SECTION
--------------------------------------------------------

  ALTER TABLE "E1818939"."SECTION" MODIFY ("CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SECTION" ADD PRIMARY KEY ("SECNO", "COURSEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SECTIONINFO
--------------------------------------------------------

  ALTER TABLE "E1818939"."SECTIONINFO" MODIFY ("SECNO" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SECTIONINFO" MODIFY ("COURSEID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SECTIONINFO" MODIFY ("ENDHOUR" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SECTIONINFO" MODIFY ("STARTHOUR" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SECTIONINFO" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SECTIONINFO" MODIFY ("DATESEC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SECTIONPROFESSOR
--------------------------------------------------------

  ALTER TABLE "E1818939"."SECTIONPROFESSOR" ADD PRIMARY KEY ("COURSEID", "SECNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPECIALSTUDENT
--------------------------------------------------------

  ALTER TABLE "E1818939"."SPECIALSTUDENT" ADD PRIMARY KEY ("STUDENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "E1818939"."SPECIALSTUDENT" MODIFY ("INSTITUTION" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SPECIALSTUDENT" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SPECIALSTUDENT" MODIFY ("NATID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SPECIALSTUDENT" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SPECIALSTUDENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."SPECIALSTUDENT" ADD CONSTRAINT "CHECK_LENSPEC" CHECK (studentID <= 99999 and studentID >=10000) ENABLE;
  ALTER TABLE "E1818939"."SPECIALSTUDENT" ADD CONSTRAINT "EMAIL_CHECKSPEC" CHECK (email like '%@%') ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "E1818939"."STAFF" ADD PRIMARY KEY ("EMPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "E1818939"."STAFF" MODIFY ("RESPONSIBILITY" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."STAFF" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."STAFF" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."STAFF" MODIFY ("NATID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."STAFF" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."STAFF" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."STAFF" ADD CONSTRAINT "CHECK_LENSTAFF" CHECK (empid <= 999 and empid >=100) ENABLE;
  ALTER TABLE "E1818939"."STAFF" ADD CONSTRAINT "EMAIL_CHACKSTAFF" CHECK (email like '%@%') ENABLE;
--------------------------------------------------------
--  Constraints for Table UNDERGRADUATE
--------------------------------------------------------

  ALTER TABLE "E1818939"."UNDERGRADUATE" ADD CONSTRAINT "CHECK_LENUNDER" CHECK (studentID >= 1000000 and studentID <= 9999999) ENABLE;
  ALTER TABLE "E1818939"."UNDERGRADUATE" ADD CONSTRAINT "EMAIL_CHECK" CHECK (email like '%@%') ENABLE;
  ALTER TABLE "E1818939"."UNDERGRADUATE" ADD PRIMARY KEY ("STUDENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "E1818939"."UNDERGRADUATE" MODIFY ("CGPA" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."UNDERGRADUATE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."UNDERGRADUATE" MODIFY ("NATID" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."UNDERGRADUATE" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "E1818939"."UNDERGRADUATE" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "E1818939"."COURSE" ADD FOREIGN KEY ("DEPTID")
	  REFERENCES "E1818939"."DEPARTMENT" ("DEPTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "E1818939"."DEPARTMENT" ADD FOREIGN KEY ("FACID")
	  REFERENCES "E1818939"."FACULTY" ("FACID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENROLLGRADUATE
--------------------------------------------------------

  ALTER TABLE "E1818939"."ENROLLGRADUATE" ADD FOREIGN KEY ("STUDENTID")
	  REFERENCES "E1818939"."GRADUATE" ("STUDENTID") ENABLE;
  ALTER TABLE "E1818939"."ENROLLGRADUATE" ADD FOREIGN KEY ("SECNO", "COURSEID")
	  REFERENCES "E1818939"."SECTION" ("SECNO", "COURSEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENROLLSPECIAL
--------------------------------------------------------

  ALTER TABLE "E1818939"."ENROLLSPECIAL" ADD FOREIGN KEY ("STUDENTID")
	  REFERENCES "E1818939"."SPECIALSTUDENT" ("STUDENTID") ENABLE;
  ALTER TABLE "E1818939"."ENROLLSPECIAL" ADD FOREIGN KEY ("SECNO", "COURSEID")
	  REFERENCES "E1818939"."SECTION" ("SECNO", "COURSEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENROLLUNDERGRADUATE
--------------------------------------------------------

  ALTER TABLE "E1818939"."ENROLLUNDERGRADUATE" ADD FOREIGN KEY ("STUDENTID")
	  REFERENCES "E1818939"."UNDERGRADUATE" ("STUDENTID") ENABLE;
  ALTER TABLE "E1818939"."ENROLLUNDERGRADUATE" ADD FOREIGN KEY ("SECNO", "COURSEID")
	  REFERENCES "E1818939"."SECTION" ("SECNO", "COURSEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRADUATE
--------------------------------------------------------

  ALTER TABLE "E1818939"."GRADUATE" ADD FOREIGN KEY ("DEPTID")
	  REFERENCES "E1818939"."DEPARTMENT" ("DEPTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREREQUISITE
--------------------------------------------------------

  ALTER TABLE "E1818939"."PREREQUISITE" ADD FOREIGN KEY ("COURSEID")
	  REFERENCES "E1818939"."COURSE" ("COURSEID") ENABLE;
  ALTER TABLE "E1818939"."PREREQUISITE" ADD FOREIGN KEY ("PREID")
	  REFERENCES "E1818939"."COURSE" ("COURSEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFADVISEDGRAD
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROFADVISEDGRAD" ADD FOREIGN KEY ("EMPID")
	  REFERENCES "E1818939"."PROFESSOR" ("EMPID") ENABLE;
  ALTER TABLE "E1818939"."PROFADVISEDGRAD" ADD FOREIGN KEY ("STUDENTID")
	  REFERENCES "E1818939"."GRADUATE" ("STUDENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFADVISEDSPEC
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROFADVISEDSPEC" ADD FOREIGN KEY ("EMPID")
	  REFERENCES "E1818939"."PROFESSOR" ("EMPID") ENABLE;
  ALTER TABLE "E1818939"."PROFADVISEDSPEC" ADD FOREIGN KEY ("STUDENTID")
	  REFERENCES "E1818939"."SPECIALSTUDENT" ("STUDENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFADVISEDUNDERGRAD
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROFADVISEDUNDERGRAD" ADD FOREIGN KEY ("EMPID")
	  REFERENCES "E1818939"."PROFESSOR" ("EMPID") ENABLE;
  ALTER TABLE "E1818939"."PROFADVISEDUNDERGRAD" ADD FOREIGN KEY ("STUDENTID")
	  REFERENCES "E1818939"."UNDERGRADUATE" ("STUDENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFESSOR
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROFESSOR" ADD FOREIGN KEY ("DEPTID")
	  REFERENCES "E1818939"."DEPARTMENT" ("DEPTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROGRAM
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROGRAM" ADD FOREIGN KEY ("DEPTID")
	  REFERENCES "E1818939"."DEPARTMENT" ("DEPTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROGRAMRELCOURSE
--------------------------------------------------------

  ALTER TABLE "E1818939"."PROGRAMRELCOURSE" ADD CONSTRAINT "PROGRAMRELCOURSE_FK1" FOREIGN KEY ("PROGID", "DEPTID")
	  REFERENCES "E1818939"."PROGRAM" ("PROGID", "DEPTID") ENABLE;
  ALTER TABLE "E1818939"."PROGRAMRELCOURSE" ADD FOREIGN KEY ("COURSEID")
	  REFERENCES "E1818939"."COURSE" ("COURSEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGISTERGRAD
--------------------------------------------------------

  ALTER TABLE "E1818939"."REGISTERGRAD" ADD CONSTRAINT "REGISTERGRAD_FK1" FOREIGN KEY ("PROGID", "DEPTID")
	  REFERENCES "E1818939"."PROGRAM" ("PROGID", "DEPTID") ENABLE;
  ALTER TABLE "E1818939"."REGISTERGRAD" ADD FOREIGN KEY ("STUDENTID")
	  REFERENCES "E1818939"."GRADUATE" ("STUDENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGISTERSPEC
--------------------------------------------------------

  ALTER TABLE "E1818939"."REGISTERSPEC" ADD CONSTRAINT "REGISTERSPEC_FK1" FOREIGN KEY ("PROGID", "DEPTID")
	  REFERENCES "E1818939"."PROGRAM" ("PROGID", "DEPTID") ENABLE;
  ALTER TABLE "E1818939"."REGISTERSPEC" ADD FOREIGN KEY ("STUDENTID")
	  REFERENCES "E1818939"."SPECIALSTUDENT" ("STUDENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGISTERUNDER
--------------------------------------------------------

  ALTER TABLE "E1818939"."REGISTERUNDER" ADD CONSTRAINT "REGISTERUNDER_FK1" FOREIGN KEY ("PROGID", "DEPTID")
	  REFERENCES "E1818939"."PROGRAM" ("PROGID", "DEPTID") ENABLE;
  ALTER TABLE "E1818939"."REGISTERUNDER" ADD FOREIGN KEY ("STUDENTID")
	  REFERENCES "E1818939"."UNDERGRADUATE" ("STUDENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SECTION
--------------------------------------------------------

  ALTER TABLE "E1818939"."SECTION" ADD FOREIGN KEY ("COURSEID")
	  REFERENCES "E1818939"."COURSE" ("COURSEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SECTIONINFO
--------------------------------------------------------

  ALTER TABLE "E1818939"."SECTIONINFO" ADD FOREIGN KEY ("SECNO", "COURSEID")
	  REFERENCES "E1818939"."SECTION" ("SECNO", "COURSEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SECTIONPROFESSOR
--------------------------------------------------------

  ALTER TABLE "E1818939"."SECTIONPROFESSOR" ADD FOREIGN KEY ("SECNO", "COURSEID")
	  REFERENCES "E1818939"."SECTION" ("SECNO", "COURSEID") ENABLE;
  ALTER TABLE "E1818939"."SECTIONPROFESSOR" ADD FOREIGN KEY ("EMPID")
	  REFERENCES "E1818939"."PROFESSOR" ("EMPID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPECIALSTUDENT
--------------------------------------------------------

  ALTER TABLE "E1818939"."SPECIALSTUDENT" ADD FOREIGN KEY ("DEPTID")
	  REFERENCES "E1818939"."DEPARTMENT" ("DEPTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "E1818939"."STAFF" ADD FOREIGN KEY ("DEPTID")
	  REFERENCES "E1818939"."DEPARTMENT" ("DEPTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UNDERGRADUATE
--------------------------------------------------------

  ALTER TABLE "E1818939"."UNDERGRADUATE" ADD FOREIGN KEY ("DEPTID")
	  REFERENCES "E1818939"."DEPARTMENT" ("DEPTID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHECK_DEPT_GRAD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "E1818939"."CHECK_DEPT_GRAD" 
BEFORE INSERT ON PROFADVISEDGRAD 
  FOR EACH ROW 
  
  DECLARE
    deptProf VARCHAR2(30);

    deptStu VARCHAR2(30);      
BEGIN
  SELECT P.DEPTID INTO deptProf FROM PROFESSOR P WHERE P.EMPID=:new.empID;
  SELECT S.DEPTID INTO deptStu FROM GRADUATE S WHERE S.STUDENTID=:new.studentId; 
  IF(deptProf!=deptStu) THEN
    ROLLBACK;
  END IF;
END;
/
ALTER TRIGGER "E1818939"."CHECK_DEPT_GRAD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHECK_DEPT_UNDER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "E1818939"."CHECK_DEPT_UNDER" 
BEFORE INSERT ON PROFADVISEDUNDERGRAD 
  FOR EACH ROW 
  
  DECLARE
    deptProf VARCHAR2(30);

    deptStu VARCHAR2(30);      
BEGIN
  SELECT P.DEPTID INTO deptProf FROM PROFESSOR P WHERE P.EMPID=:new.empID;
  SELECT S.DEPTID INTO deptStu FROM UNDERGRADUATE S WHERE S.STUDENTID=:new.studentId; 
  IF(deptProf!=deptStu) THEN
    ROLLBACK;
  END IF;
END;
/
ALTER TRIGGER "E1818939"."CHECK_DEPT_UNDER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHECK_DEPT_PROF
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "E1818939"."CHECK_DEPT_PROF" 
BEFORE INSERT ON SECTIONPROFESSOR 
  FOR EACH ROW 
  
  DECLARE
    deptProf VARCHAR2(30);

    deptCourse VARCHAR2(30);      
BEGIN
  SELECT P.DEPTID INTO deptProf FROM PROFESSOR P WHERE P.EMPID=:new.empID;
  SELECT C.DEPTID INTO deptCourse FROM COURSE C WHERE C.COURSEID=:new.courseID; 
  IF(deptProf!=deptCourse) THEN
    ROLLBACK;
  END IF;
END;
/
ALTER TRIGGER "E1818939"."CHECK_DEPT_PROF" ENABLE;
